### ISSUE TITLE
点击事件怎么实现呀

### ISSUE THREAD

**Issue by wangfufu** [fengminchao/CardBanner#1]

**Comment by fengminchao** [comment]
抱歉，现在才看到，可以在 ViewHolder 的 getView 方法中设置对这个 view 的点击事件，像这样

            ViewHolder<Integer> viewHolder = new ViewHolder<Integer>() {
            //在 ViewHolder 的 getView方法中返回最终要显示在Banner中的View, 因为考虑到项目中用 Fresco 做图片加载所以没固定写 ImageView.
                @Override
                public View getView(Context context, Integer data) {
                    ImageView imageView = new ImageView(MainActivity.this);
                    imageView.setImageResource(data);
                    imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
                    imageView.setOnClickListener(xxx);
                    return imageView;
                }

**Comment by wangfufu** [comment]
嗯嗯  已经搞定了的  多谢了
