### ISSUE TITLE
isLoop="true"

### ISSUE THREAD

**Issue by hosseinjafari9574** [fengminchao/CardBanner#3]
Hi Dear @fengminchao
I use your library and it's great :)

just I have a problem.when I use isLoop attribute, it doesn't work properly after a moment and have wrong behavior.

would you help me? 
thanks in advance 👍

**Comment by fengminchao** [comment]
> Hi Dear @fengminchao
> I use your library and it's great :)
> 
> just I have a problem.when I use isLoop attribute, it doesn't work properly after a moment and have wrong behavior.
> 
> would you help me?
> thanks in advance 👍

Thanks for your feedback. I've fixed this bug in version 1.1.1. Now you can just upgrade this library version and run. It will work fine!

**Comment by hosseinjafari9574** [comment]
thanks :)
